WARN('FAFProfiler: To activate UI Profiler press:')
WARN('FAFProfiler: Functions Profiler - Alt-P')
ConExecute('IN_BindKey Alt-P UI_Lua FuncProfilerToggle()')
WARN('FAFProfiler: Threads Profiler - Alt-O')
ConExecute('IN_BindKey Alt-O UI_Lua ThreadProfilerToggle()')
WARN('FAFProfiler: Tables Profiler - Alt-I')
ConExecute('IN_BindKey Alt-I UI_Lua TablesProfiler()')
WARN('FAFProfiler: Lines Profiler - Alt-U')
ConExecute('IN_BindKey Alt-U UI_Lua LineProfilerToggle()')